### ISSUE TITLE
How to cluster my own Dataset

### ISSUE THREAD

**Issue by hammad2008** [DeMoriarty/fast_pytorch_kmeans#9] opened 2023-03-13 11:37 UTC
@DeMoriarty  I hope you are doing well. I have the following Dataset. with four features I want to cluster the data.

Can you please provide a code for this one. I need to run it into anaconda 

I will be very thankful to you

[Dataset.csv](https://github.com/DeMoriarty/fast_pytorch_kmeans/files/10956843/Dataset.csv)

**Comment by hammad2008** [comment] 2023-03-15 04:42
@TheProjectsGuy  @DeMoriarty  Can you please help me with that?

**Comment by hammad2008** [comment] 2023-03-15 16:25
@DeMoriarty  Can you please help me with this?

**Comment by hammad2008** [comment] 2023-03-15 16:36
@DeMoriarty, I just want to use two features 2nd column and 4th column. Then apply this K-means repo, can you please modified the code for that. I will be very thankful. I have tried many methods but still does not get result always get errors

**Comment by DeMoriarty** [comment] 2023-03-15 16:40
there are many ways of choosing specific columns, if your data is already in `numpy.ndarray` or `torch.tensor` format, you can do:
```python
indices = [1, 3]
data = data[:, indices ]
```
which will select the columns with specified indices.

**Comment by hammad2008** [comment] 2023-03-15 16:42
But it does not work on your repo. The dataset has no applied using your kmeans function

**Comment by DeMoriarty** [comment] 2023-03-15 16:43
can you provide a minimal code to reproduce the error?

**Comment by hammad2008** [comment] 2023-03-15 16:55
@DeMoriarty   Here is the following Code

and the error is AttributeError: 'numpy.ndarray' object has no attribute 'device'

```
import numpy as np
array = np.loadtxt('Dataset.csv', delimiter=',')

twofeaturs = array[:, [1, 3]]
print(twofeaturs)


from fast_pytorch_kmeans import KMeans
import torch

kmeans = KMeans(n_clusters=4, mode='euclidean', verbose=1)

labels = kmeans.fit_predict(twofeaturs)


```
after solving the error i want to plot the data into different cluster

**Comment by DeMoriarty** [comment] 2023-03-15 17:04
fast_pytorch_kmeans only accepts pytorch tensors as input. all you have to do is:
```python
twofeatures = torch.from_numpy(two_features)
```
and if you want to run the kmeans algorithm on gpu, you need to:
```python
twofeatures = twofeatures.cuda()
```
before calling kmeans.fit_predict(). 

 for plotting data with labels, see #7

**Comment by hammad2008** [comment] 2023-03-15 17:09
@DeMoriarty  when i use the following code it gives the error 
UnboundLocalError: local variable 'expected' referenced before assignment

```
from fast_pytorch_kmeans import KMeans
import torch
twofeaturs = torch.from_numpy(twofeaturs)
twofeaturs = twofeaturs.cuda()
kmeans = KMeans(n_clusters=8, mode='euclidean', verbose=1)
labels = kmeans.fit_predict(twofeaturs)
```

**Comment by hammad2008** [comment] 2023-03-15 17:15
@DeMoriarty  The following is the all code but i have get the error, as shown below can you please check it

**UnboundLocalError: local variable 'expected' referenced before assignment**


```
from fast_pytorch_kmeans import KMeans
import torch
import numpy as np
array = np.loadtxt('Dataset.csv', delimiter=',')

twofeatures = array[:, [1, 3]]
print(twofeatures)
torchfeatures = torch.from_numpy(twofeatures)
gpufeature = torchfeatures.cuda()
kmeans = KMeans(n_clusters=8, mode='euclidean', verbose=1)
labels = kmeans.fit_predict(gpufeature)
plt.scatter(array[:, 0], data[:, 1], c=labels, s=10, cmap="jet")
centroids = kmeans.centroids
plt.scatter(centroids[:, 0], centroids[:, 1], s=70)
plt.show()



```

**Comment by DeMoriarty** [comment] 2023-03-15 17:20
that seems to be a bug in the KMeans, because it only recognizes float16 or float32 data, and your data is probably in float64. for a quick solution you can just convert your data into float32 or float16. to do so:
```
# float32
twofeature = twofeature.to(torch.float)
# or float16
twofeature = twofeature.to(torch.half)
```

in the meantime I will fix this bug and also add some assertions to make sure that user input is pytorch tensor. 
thanks for your contribution.

**Comment by hammad2008** [comment] 2023-03-15 17:24
@DeMoriarty After that now getting the following error 
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.



```
from fast_pytorch_kmeans import KMeans
import torch
import numpy as np
import matplotlib.pyplot as plt

array = np.loadtxt('Dataset.csv', delimiter=',')

twofeatures = array[:, [1, 3]]
print(twofeatures)
torchfeatures = torch.from_numpy(twofeatures)
gpufeature = torchfeatures.cuda()
gpufeature = gpufeature.to(torch.float)
kmeans = KMeans(n_clusters=8, mode='euclidean', verbose=1)
labels = kmeans.fit_predict(gpufeature)
plt.scatter(array[:, 0], array[:, 1], c=labels, s=10, cmap="jet")
centroids = kmeans.centroids
plt.scatter(centroids[:, 0], centroids[:, 1], s=70)
plt.show()

```

**Comment by hammad2008** [comment] 2023-03-15 17:28
@DeMoriarty  Now getting this error
**ValueError: 'c' argument has 1 elements, which is inconsistent with 'x' and 'y' with size 6610.**


```
from fast_pytorch_kmeans import KMeans
import torch
import numpy as np
import matplotlib.pyplot as plt

array = np.loadtxt('Dataset.csv', delimiter=',')

twofeatures = array[:, [1, 3]]
print(twofeatures)
torchfeatures = torch.from_numpy(twofeatures)
gpufeature = torchfeatures.cuda()
gpufeature = gpufeature.to(torch.float)
kmeans = KMeans(n_clusters=4, mode='euclidean', verbose=1)
labels = kmeans.fit_predict(gpufeature)
index = labels.cpu().data.numpy().argmax()
print(index)
plt.scatter(array[:, [0]], array[:, [1]], c=index, s=10, cmap="jet")
centroids = kmeans.centroids
plt.scatter(centroids[:, 0], centroids[:, 1], s=70)
plt.show()
```

**Comment by DeMoriarty** [comment] 2023-03-15 17:31
does this work?
```python
plt.scatter(array[:, 0], array[:, 1], c=labels.cpu(), s=10, cmap="jet")
```

**Comment by hammad2008** [comment] 2023-03-15 17:43
@DeMoriarty  no it does not work

**Comment by DeMoriarty** [comment] 2023-03-15 17:48
@hammad2008  what is the error message?

**Comment by hammad2008** [comment] 2023-03-15 17:49
@DeMoriarty  The following are my full code. The error is



**ValueError: 'c' argument has 1 elements, which is inconsistent with 'x' and 'y' with size 6610.**



```
from fast_pytorch_kmeans import KMeans
import torch
import numpy as np
import matplotlib.pyplot as plt

array = np.loadtxt('Dataset.csv', delimiter=',')

twofeatures = array[:, [1, 3]]
print(twofeatures)
torchfeatures = torch.from_numpy(twofeatures)
gpufeature = torchfeatures.cuda()
gpufeature = gpufeature.to(torch.float)
kmeans = KMeans(n_clusters=4, mode='euclidean', verbose=1)
labels = kmeans.fit_predict(gpufeature)
print(labels)
index = labels.cpu().data.numpy().argmax()
print(index)
plt.scatter(array[:, [0]], array[:, [1]], c=index, s=10, cmap="jet")
centroids = kmeans.centroids
plt.scatter(centroids[:, 0], centroids[:, 1], s=70)
plt.show()
```

**Comment by DeMoriarty** [comment] 2023-03-15 17:51
it's giving that error because you're taking argmax of the labels.

**Comment by hammad2008** [comment] 2023-03-15 17:52
@DeMoriarty  Can you please modified it and run it?

**Comment by DeMoriarty** [comment] 2023-03-15 17:53
have you tried replacing
```python
plt.scatter(array[:, [0]], array[:, [1]], c=index, s=10, cmap="jet")
``` 
with 
```python
plt.scatter(twofeatures[:, 0], twofeatures[:, 1], c=labels.cpu(), s=10, cmap="jet")
```

**Comment by hammad2008** [comment] 2023-03-15 17:54
@DeMoriarty  It also does not work.

**Comment by DeMoriarty** [comment] 2023-03-15 17:55
@hammad2008 and the error message is?

**Comment by hammad2008** [comment] 2023-03-15 17:56
@DeMoriarty AttributeError: 'numpy.ndarray' object has no attribute 'cpu'

**Comment by DeMoriarty** [comment] 2023-03-15 17:58
@hammad2008  then just remove `.cpu()`

**Comment by DeMoriarty** [comment] 2023-03-15 17:58
plt.scatter(twofeatures[:, 0], twofeatures[:, 1], c=labels, s=10, cmap="jet")

**Comment by DeMoriarty** [comment] 2023-03-15 18:39
closing since no further issues reported

**Closed by DeMoriarty** 2023-03-15 18:39 UTC
